### ISSUE TITLE
Error Building Bundle

### ISSUE THREAD

**Issue by gencube** [brix-cms/brix-cms#175] opened 2015-10-09 08:07 UTC
Failure to BUILD maven project as shown here:
https://github.com/brix-cms/brix-cms/wiki/RunningTheDemo
at this step: mvn clean install

``` bash
$ mvn clean install
...
[WARNING] Warning building bundle org.brixcms:brix-plugin-snapshot:bundle:1.3.0-SNAPSHOT : Did not find matching referal for org.osgi*
[ERROR] Error building bundle org.brixcms:brix-plugin-snapshot:bundle:1.3.0-SNAPSHOT : Unresolved references to [javax.jcr] by class(es) on the Bundle-Classpath[Jar:dot]: [org/brixcms/plugin/snapshot/ManageSnapshotsPanel$7.class]
[ERROR] Error(s) found in bundle configuration
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Brix CMS ........................................... SUCCESS [  1.479 s]
[INFO] brix-jackrabbit-testdeps ........................... SUCCESS [  0.441 s]
[INFO] Brix JCR API Wrapper ............................... SUCCESS [  6.856 s]
[INFO] Brix JCR Workspace Manager Addon ................... SUCCESS [  1.707 s]
[INFO] Brix Core .......................................... SUCCESS [  5.564 s]
[INFO] Brix Site Snapshot/Backup Plugin ................... FAILURE [  0.713 s]
[INFO] Brix Menu System Plugin ............................ SKIPPED
[INFO] Brix Site Prototypes Plugin ........................ SKIPPED
...
```

**Comment by gencube** [comment] 2015-10-09 08:09
Detail error
```bash
$ cs brix-plugin-snapsho
$  mvn -X clean install
...
[DEBUG] Bundle-Version: 1.3.0.SNAPSHOT
[DEBUG] Bundle-Name: Brix Site Snapshot/Backup Plugin
[DEBUG] Created-By: Apache Maven Bundle Plugin
[DEBUG] Build-Jdk: 1.8.0_45
[DEBUG] ------------------------------------------------------------------------
[WARNING] Warning building bundle org.brixcms:brix-plugin-snapshot:bundle:1.3.0-SNAPSHOT : Did not find matching referal for org.osgi*
[ERROR] Error building bundle org.brixcms:brix-plugin-snapshot:bundle:1.3.0-SNAPSHOT : Unresolved references to [javax.jcr] by class(es) on the Bundle-Classpath[Jar:dot]: [org/brixcms/plugin/snapshot/ManageSnapshotsPanel$7.class]
[ERROR] Error(s) found in bundle configuration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.514 s
[INFO] Finished at: 2015-10-09T15:50:28+08:00
[INFO] Final Memory: 20M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:2.1.0:bundle (default-bundle) on project brix-plugin-snapshot: Error(s) found in bundle configuration -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.felix:maven-bundle-plugin:2.1.0:bundle (default-bundle) on project brix-plugin-snapshot: Error(s) found in bundle configuration
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error(s) found in bundle configuration
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:355)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:238)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:229)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.maven.plugin.MojoFailureException: Error(s) found in bundle configuration
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:307)
	... 24 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

May I know how to solve this issue??

**Comment by kulik** [comment] 2016-06-09 11:31
Same do I, Have you find way to solve it?

**Comment by kulik** [comment] 2016-06-09 11:33
Error building bundle org.brixcms:brix-plugin-snapshot:bundle:1.3.0-SNAPSHOT : Unresolved references to [javax.jcr] by class(es) on the Bundle-Classpath[Jar:dot]: [org/brixcms/plugin/snapshot/ManageSnapshotsPanel$7.class]
[ERROR] Error(s) found in bundle configuration

**Comment by kbachl** [comment] 2017-01-17 20:15
duplicate of #182 

will fix and merge with this only on brix 8 version

**Closed by kbachl** 2017-01-17 20:15 UTC
